## numpy array를 만드는 다양한 방법

In [11]:
import numpy as np

### 파이썬 리스트를 통해 생성 => numpy.array

In [12]:

array = np.array([2,3,5,7,11,13,17,19,23,29,31])

### 균일한 값으로 생성 => numpy.full

In [13]:
''' numpy.full '''
array = np.full(6,7) # 7을 6개 배열
array

array([7, 7, 7, 7, 7, 7])

### 모든 값이 0인 배열 생성 => numpy.zeros

In [14]:
'''  numpy.zeros '''
array = np.zeros(6, dtype = int)
array

array([0, 0, 0, 0, 0, 0])

### 모든 값이 1인 배열 생성 => numpy.ones

In [15]:
''' numpy.ones '''
array = np.ones(6, dtype = int)
array

array([1, 1, 1, 1, 1, 1])

### 랜덤한 값들로 생성 => numpy.random.random

In [16]:
''' numpy.random.random '''
array = np.random.random(6)
array

array([0.01108118, 0.66840488, 0.90921685, 0.27416803, 0.18703147,
       0.69063412])

### 연속된 값들로 생성 => arange(n)

In [17]:
''' arange '''
# arange(n) = 0부터 n-1까지
array = np.arange(6)

# arange(n,m) = n부터 m-1까지
array1 = np.arange(2, 7)

# arange(n,m,s) = n부터 m-1까지 s간격
array2 = np.arange(3,17,3)

print(array, array1, array2)

[0 1 2 3 4 5] [2 3 4 5 6] [ 3  6  9 12 15]


## Indexing

In [3]:
array = np.array([2,3,5,7,9,11,13,15,17])

array[0]

2

In [4]:
array[-1]

17

In [5]:
# 한번에 여러개 indexing 하는 것도 가능
array[[1,3,6]]  

array([ 3,  7, 13])

In [6]:
# 배열을 넣어 indexing 하는 것도 가능 
array1 = np.array([2,1,3])
array[array1]

array([5, 3, 7])

## Slicing

In [7]:
# array[0:6] == array[:6]

array[0:6]

array([ 2,  3,  5,  7,  9, 11])

In [8]:
array[2:6:2]

array([5, 9])

## Numpy 기본 연산

In [22]:
arrayA = np.arange(10)
arrayB = np.arange(10,20)

### 덧셈

In [23]:
arrayA + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
arrayA + arrayB

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 뺄셈

In [26]:
arrayA - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

### 나눗셈


In [27]:
arrayA / arrayB

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [28]:
arrayB / 3

array([3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333])

### 곱셈

In [29]:
arrayA * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [30]:
arrayA * arrayB

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

## Boolean 연산

In [31]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [32]:
# array1의 원소들의 값을 비교해 해당 연산이 참이면 T 아니면 F
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
# 짝수인 애들 반환
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [34]:
booleans = np.array([True,True,False,True,True,False,True,True,True,False,True])

### numpy의 where 함수

해당 numpy array에서 True인 인덱스만 반환한다.

In [35]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10]),)

In [37]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

### Boolean을 통해 해당 조건에 부합하는 인덱스의 값 반환하기

In [39]:
# array1 > 4를 만족하는 인덱스를 filter에 저장하고 이를 인덱싱 해줌으로써
# 해당 조건을 만족시키는 배열의 값을 반환할 수 있음 
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

## Numpy 기본통계

### 최댓값과 최솟값

max 메소드와 min 메소드 이용

In [40]:
array1 = np.array([14,6,13,21,23,32,5,44])

# 최댓값
array1.max()

44

In [41]:
# 최솟값
array1.min()

5

### 중앙값

median 메소드 사용

In [42]:
np.median(array1)

17.5

In [43]:
### 표준편차와 분산

In [44]:
array1.std()

12.427288521636568

In [45]:
array1.var()

154.4375